[project]
name = "ai-tax-guidance-agent"
version = "0.1.0"
description = "AI Tax Guidance and Compliance Review Agent for Australian tax filing support"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Nishita" }
]

dependencies = [
    "langchain",
    "langchain-core",
    "langchain-community",
    "langchain-openai",
    "langchain-groq",
    "langchain-tavily",
    "langgraph",
    "python-dotenv",
    "requests",
    "beautifulsoup4",
    "tavily-python",
    "pypdf",
    "python-docx",
    "pandas",
    "openpyxl",
    "rich",
    "pydantic",
    "typing-extensions"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff"
]

[tool.ruff]
line-length = 100

[tool.pytest.ini_options]
testpaths = ["tests"]